const BATTING_POINTS = {
  RUN: 1,
  BOUNDARY_BONUS: 1,
  SIX_BONUS: 2,
  ['30_RUN_BONUS']: 4,
  HALF_CENTURY_BONUS: 8,
  CENTURY_BONUS: 16,
  DISMISSAL_FOR_A_DUCK: -2,
};

const BOWLING_POINTS = {
  WICKET: 25,
  LBW_BOWLED_BONUS: 8,
  ['3_WICKET_BONUS']: 4,
  ['4_WICKET_BONUS']: 8,
  ['5_WICKET_BONUS']: 16,
  MAIDEN_OVER: 12,
};

const FIELDING_PONITS = {
  CATCH: 8,
  ['3_CATCH_BONUS']: 4,
  STUMPING: 12,
  RUNOUT: 6,
};

export { BATTING_POINTS, BOWLING_POINTS, FIELDING_PONITS };
