import {
  BATTING_POINTS,
  BOWLING_POINTS,
  FIELDING_PONITS,
} from '../../contants.js';
function validatePlayers(allPlayers, selectedPlayers) {
  return new Promise((resolve, reject) => {
    const fullTeamPlayers = allPlayers.map((player) => player.Player);

    for (const player of selectedPlayers) {
      if (fullTeamPlayers.includes(player) === false) {
        return reject(
          new Error(
            `Player ${player} from selectedPlayers is not found in Players Data`
          )
        );
      }
    }
    const filteredPlayers = allPlayers.filter((player) =>
      selectedPlayers.includes(player.Player)
    );

    if (filteredPlayers.length > 0) {
      const checkTeamPlayerCount = filteredPlayers.filter(
        (team) => filteredPlayers[0].Team === team.Team
      );

      if (
        checkTeamPlayerCount.length === 0 ||
        checkTeamPlayerCount.length === 11
      ) {
        return reject(
          new Error(`Combination of team should be Maximum 10 minimum 1`)
        );
      }
    }

    resolve('All players in selectedPlayers are included in Player Data.');
  });
}

function calculatePlayerPoints(matchData) {
  const playerPoints = {};

  const playerRun = {};

  // matchData = [
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01de',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 1,
  //     ballnumber: 4,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01e0',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 1,
  //     ballnumber: 6,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01e7',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 3,
  //     ballnumber: 1,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01e8',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 3,
  //     ballnumber: 2,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01eb',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 3,
  //     ballnumber: 5,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01ef',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 4,
  //     ballnumber: 3,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01f2',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 4,
  //     ballnumber: 6,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01f7',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 5,
  //     ballnumber: 5,
  //     batter: 'MM Ali',
  //     bowler: 'TA Boult',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01fd',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 6,
  //     ballnumber: 5,
  //     batter: 'MM Ali',
  //     bowler: 'YS Chahal',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0204',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 7,
  //     ballnumber: 6,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'N Jagadeesan',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd021d',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 11,
  //     ballnumber: 5,
  //     batter: 'MM Ali',
  //     bowler: 'TA Boult',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd022c',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 13,
  //     ballnumber: 6,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0239',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 16,
  //     ballnumber: 1,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd023c',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 16,
  //     ballnumber: 4,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0243',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 17,
  //     ballnumber: 5,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0244',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 17,
  //     ballnumber: 6,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0249',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 18,
  //     ballnumber: 5,
  //     batter: 'MM Ali',
  //     bowler: 'YS Chahal',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01df',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 1,
  //     ballnumber: 5,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01e9',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 3,
  //     ballnumber: 3,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01ee',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 4,
  //     ballnumber: 2,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01f0',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 4,
  //     ballnumber: 4,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01f1',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 4,
  //     ballnumber: 5,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 6,
  //     extrasRun: 0,
  //     totalRun: 6,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01f5',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 5,
  //     ballnumber: 3,
  //     batter: 'MM Ali',
  //     bowler: 'TA Boult',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01f8',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 5,
  //     ballnumber: 6,
  //     batter: 'MM Ali',
  //     bowler: 'TA Boult',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01fc',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 6,
  //     ballnumber: 4,
  //     batter: 'MM Ali',
  //     bowler: 'YS Chahal',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01ff',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 7,
  //     ballnumber: 1,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'DP Conway',
  //     extraType: 'wides',
  //     batsmanRun: 0,
  //     extrasRun: 1,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0205',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 7,
  //     ballnumber: 7,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'N Jagadeesan',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0206',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 8,
  //     ballnumber: 1,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'N Jagadeesan',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd020f',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 9,
  //     ballnumber: 4,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'AT Rayudu',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd021a',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 11,
  //     ballnumber: 2,
  //     batter: 'MM Ali',
  //     bowler: 'TA Boult',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd021f',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 12,
  //     ballnumber: 1,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'wides',
  //     batsmanRun: 0,
  //     extrasRun: 1,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0228',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 13,
  //     ballnumber: 2,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0231',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 14,
  //     ballnumber: 5,
  //     batter: 'MM Ali',
  //     bowler: 'YS Chahal',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0245',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 18,
  //     ballnumber: 1,
  //     batter: 'MM Ali',
  //     bowler: 'YS Chahal',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0246',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 18,
  //     ballnumber: 2,
  //     batter: 'MM Ali',
  //     bowler: 'YS Chahal',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01dd',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 1,
  //     ballnumber: 3,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01ea',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 3,
  //     ballnumber: 4,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 6,
  //     extrasRun: 0,
  //     totalRun: 6,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01f3',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 5,
  //     ballnumber: 1,
  //     batter: 'MM Ali',
  //     bowler: 'TA Boult',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 6,
  //     extrasRun: 0,
  //     totalRun: 6,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01f4',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 5,
  //     ballnumber: 2,
  //     batter: 'MM Ali',
  //     bowler: 'TA Boult',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01f6',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 5,
  //     ballnumber: 4,
  //     batter: 'MM Ali',
  //     bowler: 'TA Boult',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0211',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 9,
  //     ballnumber: 6,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'AT Rayudu',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0220',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 12,
  //     ballnumber: 2,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0222',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 12,
  //     ballnumber: 4,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'wides',
  //     batsmanRun: 0,
  //     extrasRun: 1,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0225',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 12,
  //     ballnumber: 7,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0229',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 13,
  //     ballnumber: 3,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0232',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 14,
  //     ballnumber: 6,
  //     batter: 'MM Ali',
  //     bowler: 'YS Chahal',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0238',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 15,
  //     ballnumber: 6,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd023b',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 16,
  //     ballnumber: 3,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 4,
  //     extrasRun: 0,
  //     totalRun: 4,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd023e',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 16,
  //     ballnumber: 6,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01ec',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 3,
  //     ballnumber: 6,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd01fa',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 6,
  //     ballnumber: 2,
  //     batter: 'MM Ali',
  //     bowler: 'YS Chahal',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0200',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 7,
  //     ballnumber: 2,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'DP Conway',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd020e',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 9,
  //     ballnumber: 3,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'AT Rayudu',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0213',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 10,
  //     ballnumber: 1,
  //     batter: 'MM Ali',
  //     bowler: 'YS Chahal',
  //     nonStriker: 'AT Rayudu',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0223',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 12,
  //     ballnumber: 5,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd022a',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 13,
  //     ballnumber: 4,
  //     batter: 'MM Ali',
  //     bowler: 'R Ashwin',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd0233',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 15,
  //     ballnumber: 1,
  //     batter: 'MM Ali',
  //     bowler: 'M Prasidh Krishna',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 1,
  //     extrasRun: 0,
  //     totalRun: 1,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd023a',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 16,
  //     ballnumber: 2,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 2,
  //     extrasRun: 0,
  //     totalRun: 2,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd023d',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 16,
  //     ballnumber: 5,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'MS Dhoni',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 0,
  //     playerOut: 'NA',
  //     kind: 'NA',
  //     fieldersInvolved: 'NA',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  //   {
  //     _id: {
  //       $oid: '665bf3065445135e1abd024c',
  //     },
  //     ID: 1304114,
  //     innings: 1,
  //     overs: 19,
  //     ballnumber: 1,
  //     batter: 'MM Ali',
  //     bowler: 'OC McCoy',
  //     nonStriker: 'MJ Santner',
  //     extraType: 'NA',
  //     batsmanRun: 0,
  //     extrasRun: 0,
  //     totalRun: 0,
  //     nonBoundary: 0,
  //     isWicketDelivery: 1,
  //     playerOut: 'MM Ali',
  //     kind: 'caught',
  //     fieldersInvolved: 'R Parag',
  //     battingTeam: 'Chennai Super Kings',
  //   },
  // ];

  matchData.forEach((ball) => {
    const {
      batter,
      bowler,
      batsmanRun,
      isWicketDelivery,
      kind,
      fieldersInvolved,
    } = ball;

    // Initialize player points if not already done
    if (!playerPoints[batter]) playerPoints[batter] = 0;
    if (!playerPoints[bowler]) playerPoints[bowler] = 0;
    if (fieldersInvolved && fieldersInvolved !== 'NA') {
      fieldersInvolved.split(',').forEach((fielder) => {
        if (!playerPoints[fielder]) playerPoints[fielder] = 0;
      });
    }

    if (!playerRun[batter]) playerRun[batter] = 0;
    if (!playerRun[bowler]) playerRun[bowler] = 0;
    if (fieldersInvolved && fieldersInvolved !== 'NA') {
      fieldersInvolved.split(',').forEach((fielder) => {
        if (!playerRun[fielder]) playerRun[fielder] = 0;
      });
    }

    // Batting points
    playerPoints[batter] += batsmanRun * BATTING_POINTS.RUN;

    playerRun[batter] += batsmanRun;

    if (batsmanRun === 4) playerPoints[batter] += BATTING_POINTS.BOUNDARY_BONUS;
    if (batsmanRun === 6) playerPoints[batter] += BATTING_POINTS.SIX_BONUS;

    // Check for wickets
    if (isWicketDelivery) {
      if (kind === 'bowled' || kind === 'lbw') {
        playerPoints[bowler] +=
          BOWLING_POINTS.WICKET + BOWLING_POINTS.LBW_BOWLED_BONUS;
      } else if (kind === 'caught and bowled') {
        playerPoints[bowler] += FIELDING_PONITS.CATCH + BOWLING_POINTS.WICKET;
      } else {
        playerPoints[bowler] += BOWLING_POINTS.WICKET;
      }

      if (kind === 'caught' || kind === 'bowled') {
        const catcher = fieldersInvolved;
        playerPoints[catcher] += FIELDING_PONITS.CATCH;
      }

      if (kind === 'stumping') {
        const stumper = fieldersInvolved;
        playerPoints[stumper] += FIELDING_PONITS.STUMPING;
      }
    }
  });

  console.log('playerRun', playerRun);

  delete playerPoints['NA'];

  for (const [player, points] of Object.entries(playerRun)) {
    if (points >= 30 && points <= 50) {
      playerPoints[player] += BATTING_POINTS['30_RUN_BONUS'];
    }
    if (points >= 50 && points <= 100) {
      playerPoints[player] += BATTING_POINTS['HALF_CENTURY_BONUS'];
    }
    if (points >= 100) {
      playerPoints[player] += BATTING_POINTS['CENTURY_BONUS'];
    }
  }

  return playerPoints;
}

function generateMatchResult(matchSummary) {
  const team1 = matchSummary[0];
  const team2 = matchSummary[1];

  const firstInnings = team1.innings === 1 ? team1 : team2;
  const secondInnings = team1.innings === 2 ? team1 : team2;

  let result;
  if (secondInnings.totalRuns > firstInnings.totalRuns) {
    const wicketsRemaining = 10 - secondInnings.totalWickets;
    result = `${secondInnings._id} won the match by ${wicketsRemaining} wickets`;
  } else {
    const runsDifference = firstInnings.totalRuns - secondInnings.totalRuns;
    result = `${firstInnings._id} won the match by ${runsDifference} runs`;
  }

  return result;
}

export { validatePlayers, calculatePlayerPoints, generateMatchResult };
